# Cloudflare Pages 配置
# 注意：这个文件主要用于 wrangler pages 命令
# 对于 Pages 部署，大部分配置在 Cloudflare Dashboard 中设置

name = "otis-assistant-pwa"
compatibility_date = "2025-07-18"

# Pages 项目配置
pages_build_output_dir = "."